ADprojrct-System-master/Inventory/Inventory-mvc/Controllers/RaiseRequisitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_mvc.Models;
using Inventory_mvc.ViewModel;
using Inventory_mvc.Service;
using PagedList;
using Inventory_mvc.Function;
using Inventory_mvc.Utilities;

namespace Inventory_mvc.Controllers
{
    public class RaiseRequisitionController : Controller
    {
        IStationeryService stationeryService = new StationeryService();
        IRequisitionRecordService requisitionService = new RequisitionRecordService();
        IUserService userService = new UserService();

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult BrowseCatalogue(string searchString, int? page, string categoryID = "-1")
        {
            List<Stationery> stationeries = stationeryService.GetStationeriesBasedOnCriteria(searchString, categoryID);

            ViewBag.CategoryList = stationeryService.GetAllCategory();
            ViewBag.CategoryID = (categoryID == "-1") ? "-1" : categoryID;

            ViewBag.SearchString = searchString;
            ViewBag.Page = page;

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(stationeries.ToPagedList(pageNumber, pageSize));
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult ResetCatalogue()
        {
            return RedirectToAction("BrowseCatalogue", new { searchString = "", categoryID = "-1" });
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult NewRequisition(string type, string itemCode = null)
        {
            List<RaiseRequisitionViewModel> requestList = Session["RequestList"] as List<RaiseRequisitionViewModel>;

            if(requestList == null)
            {
                // to fix weird situation where when session start the list didnt initialize
                requestList = new List<RaiseRequisitionViewModel>();
                Session["RequestList"] = requestList;
            }

            if (!String.IsNullOrEmpty(itemCode) && type == "remove") // to show message after remove item
            {
                Stationery s = stationeryService.FindStationeryByItemCode(itemCode);
                TempData["SuccessMessage"] = String.Format("{0} was removed.", s.description);
            }

            return View(requestList);
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        [HttpPost]
        public void SaveTemporaryValue(List<RaiseRequisitionViewModel> requestList)
        {
            // to reserve edited quantity value when press Add Item button
            if(requestList != null)
            {
                Session["RequestList"] = requestList;
            }
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        [HttpPost]
        public ActionResult AddNewRequestItem(string itemCode, int quantity, string searchString, int? page, string categoryID)
        {
            List<RaiseRequisitionViewModel> requestList = Session["RequestList"] as List<RaiseRequisitionViewModel>;

            if (requestList == null)
            {
                // to fix weird situation where when session start the list didnt initialize
                requestList = new List<RaiseRequisitionViewModel>();
                Session["RequestList"] = requestList;
            }


            // Server side validation
            if (quantity < 1)
            {
                string addItemErrorMessage = String.Format("Quantity must be greater than or equal to 1.");
                TempData["ErrorMessage"] = addItemErrorMessage;
            }
            else
            {
                Stationery stationery = stationeryService.FindStationeryByItemCode(itemCode);

                RaiseRequisitionViewModel vm = new RaiseRequisitionViewModel();
                vm.Description = stationery.description;
                vm.ItemCode = stationery.itemCode;
                vm.Quantity = quantity;
                vm.UOM = stationery.unitOfMeasure;

                bool contain = false;
                foreach (var request in requestList)
                {
                    if (request.ItemCode == vm.ItemCode)
                    {
                        request.Quantity += vm.Quantity;
                        contain = true;
                        break;
                    }
                }
                if (!contain)
                {
                    requestList.Add(vm);
                }
                Session["RequestList"] = requestList;

                string addItemMessage = String.Format("{0} x {1} was added into requisition form.", vm.Quantity, vm.Description);
                TempData["SuccessMessage"] = addItemMessage;
            }

            ViewBag.SearchString = searchString;
            ViewBag.CategoryID = categoryID;
            ViewBag.Page = page;

            string path = Request.UrlReferrer.ToString();
            if(path.Contains("NewRequisition"))
            {
                return RedirectToAction("NewRequisition");
            }
            else
            {
                // to return to same search page after go back to catalogue
                return RedirectToAction("BrowseCatalogue",
                        new { searchString = searchString, categoryID = categoryID, page = page });
            }
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        [HttpPost]
        public ActionResult RemoveRequestItem(string itemCode, List<RaiseRequisitionViewModel> requestList)
        {
            RaiseRequisitionViewModel vm = requestList.Find(x => x.ItemCode == itemCode);
            string itemDescription = vm.Description;
            requestList.Remove(vm);
            Session["RequestList"] = requestList;

            TempData["SuccessMessage"] = String.Format("{0} was removed.", itemDescription);

            return RedirectToAction("NewRequisition");
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        [HttpPost]
        public ActionResult SubmitRequisition(List<RaiseRequisitionViewModel> requestList)
        {
            string requesterID = HttpContext.User.Identity.Name;

            Requisition_Record requisition = new Requisition_Record();
            
            foreach(RaiseRequisitionViewModel request in requestList)
            {
                Requisition_Detail rd = new Requisition_Detail();
                rd.itemCode = request.ItemCode;
                rd.qty = request.Quantity;
                rd.allocatedQty = 0;
                rd.fulfilledQty = 0;

                requisition.Requisition_Detail.Add(rd);
            }

            if(!requisitionService.IsUserValidToSubmitRequisition(requesterID))
            {
                TempData["ErrorMessage"] = "Sorry, you are not allowed to submit stationery requisition.";
                return RedirectToAction("NewRequisition");
            }

            if (requisitionService.ValidateRequisition(requisition))
            {
                // Valid request, submit to database
                try
                {
                    requisitionService.SubmitNewRequisition(requisition, requesterID);

                    // clear requestlist
                    Session["RequestList"] = new List<RaiseRequisitionViewModel>();
                    TempData["SuccessMessage"] = "New stationery requisition has been submitted.";

                    // go to user requisition list
                    return RedirectToAction("Index", "ListRequisitions");
                }
                catch (EmailException e)
                {
                    // submit requisition successfully but email throw exception

                    // clear requestlist
                    Session["RequestList"] = new List<RaiseRequisitionViewModel>();
                    TempData["SuccessMessage"] = "New stationery requisition has been submitted.";
                    TempData["WarningMessage"] = "Failure to send email notification. Kindly contact IT personnel.";

                    // go to user requisition list
                    return RedirectToAction("Index", "ListRequisitions");
                }
                catch (Exception e1)
                {
                    // error
                    Session["RequestList"] = requestList;
                    TempData["ErrorMessage"] = e1.Message;
                }
            }
            else
            {
                // Invalid request
                Session["RequestList"] = requestList;
                TempData["ErrorMessage"] = "Invalid request";
            }

            //return to new requisition form if submit unsuccessful
            return RedirectToAction("NewRequisition");
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult ClearAllRequestItem()
        {
            List<RaiseRequisitionViewModel> requestList = Session["RequestList"] as List<RaiseRequisitionViewModel>;
            requestList.Clear();
            Session["RequestList"] = requestList;

            TempData["SuccessMessage"] = String.Format("All items were removed.");

            return RedirectToAction("NewRequisition");
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult GetStationeryListJSON(string term = null)
        {
            List<JSONForCombobox> options = new List<JSONForCombobox>();

            List<Stationery> stationeries = stationeryService.GetStationeriesBasedOnCriteria(term);

ADprojrct-System-master/Inventory/Inventory-mvc/Views/RaiseRequisition/BrowseCatalogue.cshtml
@model PagedList.IPagedList<Inventory_mvc.Models.Stationery>

@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Browse Stationery Catalogue";

    List<Inventory_mvc.Models.Category> categoryList = ViewBag.CategoryList;

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];    
}


<h2>Stationery Catalogue</h2>



@using (Html.BeginForm("BrowseCatalogue", "RaiseRequisition", FormMethod.Get, new { @class = "form-inline" }))
{

    <table class="table pagination">
        <tr>
            <td>
                @Html.Label("Description", new { @class = "col-sm-2 col-form-label" })
            </td>
            <td>
                @Html.TextBox("searchString", ViewBag.SearchString as string, new { @class = "form-control mx-sm-3" })
            </td>
            <td>
                @Html.Label("Category", new { @class = "col-sm-2 col-form-label" })
            </td>
            <td>
                <select name="categoryID" class="form-control">
                    <option value="-1" selected="selected">All</option>
                    @foreach (var category in categoryList)
                    {
                        string selected = "";

                        if (ViewBag.CategoryID == category.categoryID.ToString())
                        {
                            selected = "selected";
                        }
                        <option value="@category.categoryID" @selected> @category.categoryName </option>
                    }
                </select>
            </td>
            <td>
                <input type="submit" class="btn btn-primary" value="Search" />

                @Html.ActionLink("Reset", "ResetCatalogue", "RaiseRequisition", null, new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>
}


@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}



<table class="table table-responsive">
    <tr>
        <th>
            @Html.Label("Category")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().unitOfMeasure)
        </th>
        <th>
            @Html.Label("Add Request")
        </th>
    </tr>

    @foreach (var item in Model)
            {
                using (Html.BeginForm("AddNewRequestItem", "RaiseRequisition", new { itemCode = item.itemCode, searchString = ViewBag.SearchString, categoryID = ViewBag.CategoryID, page = ViewBag.Page }, FormMethod.Post, new { @class = "form" }))
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.categoryName)
                </td>
                <td>
                    @Html.HiddenFor(modelItem => item.itemCode)
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.unitOfMeasure)
                </td>
                <td>
                    <div class="form-inline">
                        <input type="number" name="quantity" value="0" min="1" max="100" class="form-control" placeholder="Quantity" />
                        <input type="submit" value="Add" class="btn btn-success" />
                    </div>
                </td>
            </tr>
        }
    }
</table>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("BrowseCatalogue",
                     new { searchString = ViewBag.SearchString, categoryID = ViewBag.CategoryID, page }))


        @Html.ActionLink("Go To Requisition Form", "NewRequisition", "RaiseRequisition", null, new { @class = "btn btn-primary" })

<br />

ADprojrct-System-master/Inventory/Inventory-mvc/Views/RaiseRequisition/NewRequisition.cshtml
<script src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />

@model IEnumerable<Inventory_mvc.ViewModel.RaiseRequisitionViewModel>


@{
    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
}

<h2>Requisition Form</h2>

<br />
<button type="button" class="btn btn-success" id="addItemBtn" data-toggle="modal" data-target="#addItemModal">Add New Item</button>
@Html.ActionLink("Go To Catalogue", "BrowseCatalogue", null, new { @class = "btn btn-primary" })
<br />
<br />

@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

<br />

@if (Model.Count() == 0)
{
    <h4><i>Your requisition form is empty.</i></h4>
}
else
{
    using (Html.BeginForm("SubmitRequisition", "RaiseRequisition", FormMethod.Post, new { @class = "form", @id="requestForm" }))
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UOM)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Quantity)
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    var item = Model.ElementAt(i);

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                            <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode" />
                            <input type="hidden" name="[@i].Description" value="@item.Description" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UOM)
                            <input type="hidden" name="[@i].UOM" value="@item.UOM" />
                        </td>
                        <td>
                            <input type="number" name="[@i].Quantity" value="@item.Quantity" class="form-control form-control-sm" min="1" max="100" required/>
                        </td>
                        <td>
                            <a href="#" data-bind="@item.ItemCode" onclick="RemoveItem('@item.ItemCode')" class="removeBtn">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <br />

        <input type="submit" value="Submit Requisition" class="btn btn-success" onclick = "return confirm('Are you sure you want to submit the requisition?');" />
        <a href="@Url.Action("ClearAllRequestItem", "RaiseRequisition" )">
            <input type="button" value="Clear All" class="btn btn-danger" onclick = "return confirm('Are you sure you want to clear all items in the form?');"/>
        </a>

        <br />
    }
}


<!-- The below code is for the modal dialog -->
<div class="modal fade" id="addItemModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="addItemModalBodyDiv">
            @using (Html.BeginForm("AddNewRequestItem", "RaiseRequisition", FormMethod.Post, new { @class = "form", id = "itemForm" }))
            {
                <div class="modal-header">
                    <h3 class="modal-title">Add Stationery Request</h3>
                </div>

                <div class="modal-body">

                    <div class="form-group">
                        @Html.Label("Stationery")
                        <br />
                        <!-- Combobox -->
                        <select class="js-data-example-ajax js-states form-control" style="width: 100%" name="itemCode" required>
                            <option></option>
                        </select>
                    </div>

                    <div class="form-group">
                        @Html.Label("Quantity")
                        <input type="number" name="quantity" value="1" min="1" class="form-control" required/>
                    </div>
                </div>

                <div class="modal-footer">
                    <input type="submit" value="Add" class="btn btn-success" />
                    <input type="button" value="Cancel" class="btn btn-secondary" data-dismiss="modal" />
                </div>
            }
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('.js-data-example-ajax').select2({
            ajax: {
                url: '@Url.Action("GetStationeryListJSON", "RaiseRequisition")',
                delay: 250,
                dataType: 'json',
             
                processResults: function (data) {
                    return {
                        results: data
                    };
                },
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
            },

            placeholder: "Select a stationery",
            //minimumInputLength: 1,
            selectOnClose: true,
            allowClear: true,
            dropdownParent: $('#addItemModal'),
        });

        $(".removeBtn").click(function () {
            var itemCode = $(this).data("bind");


            var myformdata = $("#requestForm").serializeArray(); // convert form to array
            myformdata.push({ name: "itemCode", value: itemCode }); // add extra key-value pair

            $.ajax({
                type: "POST",
                url: '@Url.Action("RemoveRequestItem", "RaiseRequisition")',
                data: $.param(myformdata), // convert to url-encoded form
                success: function () {
                    window.location.href = '@Url.Action("NewRequisition", "RaiseRequisition")?type=remove&itemCode=' + itemCode;
                }
            });
        });


        $("#addItemBtn").click(function () {

            var myformdata = $("#requestForm").serializeArray(); // convert form to array

            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveTemporaryValue", "RaiseRequisition")',
                data: $.param(myformdata), // convert to url-encoded form
            });
        });


    });

</script>

ADprojrct-System-master/Inventory/Inventory-mvc/Views/RaiseRequisition/_CreateEditPartial.cshtml
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

@model Inventory_mvc.ViewModel.RaiseRequisitionViewModel

@{
    var buttonName = "Add";
    var action = "AddNewRequestItem";

    if (!String.IsNullOrEmpty(Model.ItemCode))
    {
        buttonName = "Save Change";
        action = "EditRequestItem";
    }
}

@using (Html.BeginForm(action.ToString(), "RaiseRequisition", FormMethod.Post, new { @class = "form", id = "requestForm" }))
{
    <div class="modal-header">
        <h3 class="modal-title">Stationery Request</h3>
    </div>

    <div class="modal-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (action == "AddNewRequestItem")
        {
            <div class="form-group">
                @Html.Label("Select a stationery")
                @Html.DropDownListFor(model => model.ItemCode, ViewBag.SelectList as List<SelectListItem>, htmlAttributes: new { @class = "form-control", id = "ddl" })
                @Html.ValidationMessageFor(model => model.ItemCode, "", new { @class = "text-danger" })
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.Label("Stationery")
                <input class="form-control" type="text" value="@Model.Description" readonly/>
                @Html.HiddenFor(model => model.ItemCode)
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity)
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", id = "qty", value = "1", min = "1" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="modal-footer">
        <input type="submit" value="@buttonName" class="btn btn-success" />
        <input type="button" value="Cancel" class="btn btn-secondary" data-dismiss="modal" />
    </div>
}

<script>

</script>