ADprojrct-System-master/Inventory/Inventory-mvc/Controllers/AdjustmentVoucherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_mvc.Service;
using Inventory_mvc.Models;
using Inventory_mvc.ViewModel;
using Inventory_mvc.Function;
using Inventory_mvc.Utilities;
using PagedList;

namespace Inventory_mvc.Controllers
{
    public class AdjustmentVoucherController : Controller
    {
        IStationeryService stationeryService = new StationeryService();
        IUserService userService = new UserService();
        IAdjustmentVoucherService adjustmentVoucherService = new AdjustmentVoucherService();

        // CK - Store Supervisor | Store Manager
        [RoleAuthorize]
        public ActionResult Index(string status, int? page, string sortOrder)
        {
            string approverID = HttpContext.User.Identity.Name;

            // Set Filter criteria
            status = (String.IsNullOrEmpty(status)) ? AdjustmentVoucherStatus.PENDING : status;
            ViewBag.Status = status;

            List<SelectListItem> statusSelectList = new List<SelectListItem>();
            statusSelectList.Add(new SelectListItem { Text = AdjustmentVoucherStatus.PENDING, Value = AdjustmentVoucherStatus.PENDING });
            statusSelectList.Add(new SelectListItem { Text = AdjustmentVoucherStatus.APPROVED, Value = AdjustmentVoucherStatus.APPROVED });
            statusSelectList.Add(new SelectListItem { Text = AdjustmentVoucherStatus.REJECTED, Value = AdjustmentVoucherStatus.REJECTED });
            foreach (var s in statusSelectList)
            {
                if (s.Value == ViewBag.Status)
                {
                    s.Selected = true;
                }
            }
            ViewBag.SelectStatus = statusSelectList;

            if (String.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "number_desc"; // make default sorting by voucher number desc
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NumberSortParm = (sortOrder == "Voucher Number") ? "number_desc" : "Voucher Number";
            ViewBag.RequesterSortParm = (sortOrder == "Issued By") ? "issued_by_desc" : "Issued By";

            List<AdjustmentVoucherViewModel> vouchers = adjustmentVoucherService.GetVoucherRecordsByCriteria(approverID, status, sortOrder);

            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(vouchers.ToPagedList(pageNumber, pageSize));
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        public ActionResult NewVoucher(string type, string itemCode = null)
        {
            List<AdjustmentVoucherViewModel> vmList = Session["NewVoucher"] as List<AdjustmentVoucherViewModel>;

            if (vmList == null)
            {
                vmList = new List<AdjustmentVoucherViewModel>();
                Session["NewVoucher"] = vmList;
            }

            if (!String.IsNullOrEmpty(itemCode) && type == "remove") // use to display message if remove item from voucher
            {
                TempData["SuccessMessage"] = String.Format("{0} was removed.", itemCode);
            }

            return View(vmList);
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        [HttpPost]
        public ActionResult AddItemIntoVoucher(string itemCode, int quantity, string reason)
        {
            Stationery s = stationeryService.FindStationeryByItemCode(itemCode);

            if ((s.stockQty + quantity) < 0)
            {
                // cannot minus more than current stock
                TempData["ErrorMessage"] = String.Format("Negative adjustment quantity cannot greater than current stock.");
            }
            else
            {
                List<AdjustmentVoucherViewModel> vmList = Session["NewVoucher"] as List<AdjustmentVoucherViewModel>;

                AdjustmentVoucherViewModel vm = new AdjustmentVoucherViewModel();
                vm.ItemCode = itemCode;
                vm.Quantity = quantity;
                vm.Reason = reason;
                vm.StationeryDescription = s.description;
                vm.UOM = s.unitOfMeasure;
                vm.Price = s.price;

                bool contain = false;
                bool zeroQuantity = (quantity == 0) ? true : false;

                foreach (var item in vmList)
                {
                    if (item.ItemCode == vm.ItemCode)
                    {
                        item.Quantity += vm.Quantity;
                        contain = true;
                        zeroQuantity = (item.Quantity == 0) ? true : false; // notify user if quantity become 0
                        break;
                    }
                }
                if (!contain)
                {
                    vmList.Add(vm);
                }

                Session["NewVoucher"] = vmList;

                TempData["SuccessMessage"] = String.Format("{0} was added.", itemCode);
                TempData["WarningMessage"] = (zeroQuantity) ? String.Format("Warning! Quantity of {0} is 0, which will not be submitted.", itemCode) : null;
            }

            return RedirectToAction("NewVoucher");
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        [HttpPost]
        public void SaveTemporaryValue(List<AdjustmentVoucherViewModel> vmList)
        {
            // to reserve edited quantity value when press Add Item button
            if (vmList != null)
            {
                Session["NewVoucher"] = vmList;
            }
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        [HttpPost]
        public ActionResult RemoveVoucherItem(string itemCode, List<AdjustmentVoucherViewModel> vmList)
        {
            AdjustmentVoucherViewModel vm = vmList.Find(x => x.ItemCode == itemCode);
            vmList.Remove(vm);
            Session["NewVoucher"] = vmList;

            TempData["SuccessMessage"] = String.Format("{0} was removed.", itemCode);

            return RedirectToAction("NewVoucher");
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        [HttpPost]
        public ActionResult SubmitVoucher(List<AdjustmentVoucherViewModel> vmList)
        {
            string requesterID = HttpContext.User.Identity.Name;
            string errorMessage;

            if (adjustmentVoucherService.ValidateNewAdjustmentVoucher(vmList, out errorMessage))
            {
                // Valid voucher
                try
                {
                    adjustmentVoucherService.SubmitNewAdjustmentVoucher(vmList, AdjustmentVoucherRemarks.RECONCILE, requesterID);
                    
                    // clear list
                    Session["NewVoucher"] = new List<AdjustmentVoucherViewModel>();
                    TempData["SuccessMessage"] = String.Format("Adjustment voucher has been submitted for approval.");                   
                }
                catch(EmailException e)
                {
                    // clear list
                    Session["NewVoucher"] = new List<AdjustmentVoucherViewModel>();
                    TempData["SuccessMessage"] = String.Format("Adjustment voucher has been submitted for approval.");

                    TempData["WarningMessage"] = "Failure to send email notification. Kindly contact IT personnel.";
                }
                catch (Exception e1)
                {
                    TempData["ErrorMessage"] = String.Format("Error writing new adjustment voucher into database");
                }
            }
            else
            {
                TempData["ErrorMessage"] = errorMessage;
            }

            return RedirectToAction("NewVoucher");
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        public ActionResult ClearAllItemInVoucher()
        {
            List<AdjustmentVoucherViewModel> vmList = Session["NewVoucher"] as List<AdjustmentVoucherViewModel>;
            vmList.Clear();
            Session["RequestList"] = vmList;

            TempData["SuccessMessage"] = String.Format("All items were removed.");

            return RedirectToAction("NewVoucher");
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        public ActionResult GetStationeryListJSON(string term = null)
        {
            List<JSONForCombobox> options = new List<JSONForCombobox>();

            List<Stationery> stationeries = stationeryService.GetStationeriesBasedOnCriteria(term);
            foreach (var s in stationeries)
            {
                JSONForCombobox option = new JSONForCombobox();
                option.id = s.itemCode;
                option.text = String.Format("{0} ({1})", s.itemCode, s.description);
                options.Add(option);
            }
            return Json(options, JsonRequestBehavior.AllowGet);
        }

        [RoleAuthorize]
        // CK - Store Supervisor | Store Manager
        public ActionResult ShowDetail(int? id)
        {
            int voucherNo = (id == null) ? -1 : (int)id;

            if (voucherNo == -1)
            {
                return RedirectToAction("Index");
            }


            string approverID = HttpContext.User.Identity.Name;

            string errorMessage;
            List<AdjustmentVoucherViewModel> vmList = adjustmentVoucherService.IsUserAuthorizedToViewVoucherDetail(voucherNo, approverID, out errorMessage);

            if (!String.IsNullOrEmpty(errorMessage))
            {
                TempData["ErrorMessage"] = errorMessage;
                return RedirectToAction("Index");
            }

            return View(vmList);
        }

        [RoleAuthorize]
        // CK - Store Supervisor | Store Manager
        [HttpGet]
        public ActionResult MakeApproval(int? id)
        {

ADprojrct-System-master/Inventory/Inventory-mvc/Views/AdjustmentVoucher/Index.cshtml
@model PagedList.IPagedList<Inventory_mvc.ViewModel.AdjustmentVoucherViewModel>

@using PagedList.Mvc;
@using System.Globalization;
@using Inventory_mvc.Utilities;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Index";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];

    Inventory_mvc.ViewModel.AdjustmentVoucherViewModel model = null;

    if (Model.Count() != 0)
    {
        model = Model.First();
    }
}


<h2>Adjustment Voucher List</h2>
<br />

@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}


@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@using (Html.BeginForm("Index", "AdjustmentVoucher", FormMethod.Get, new { @class = "form"}))
{
<table class="table pagination">
    <tr>
        <td>
            @Html.Label("Filter By Status", new { @class = "text-right font-weight-bold" })
        </td>
        <td>
            @Html.DropDownList("status", ViewBag.SelectStatus as IEnumerable<SelectListItem>, new { @class = "form-control", onchange = "form.submit();" })
        </td>
    </tr>
</table>


if (ViewBag.Status == AdjustmentVoucherStatus.PENDING)
{
    if (Model.Count() == 0)
    {
        <h4><i>There is not voucher pending approval.</i></h4>
        <br />
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("Voucher Number", "Index", new { sortOrder = ViewBag.NumberSortParm, status = ViewBag.Status })
                    </th>
                    <th>
                        @Html.DisplayNameFor(i => model.IssueDate)
                    </th>
                    <th>
                        @Html.ActionLink("Issued By", "Index", new { sortOrder = ViewBag.RequesterSortParm, status = ViewBag.Status })
                    </th>
                    <th>
                        @Html.DisplayNameFor(i => model.Causes)
                    </th>
                    <th>
                        @Html.DisplayNameFor(i => model.VoucherTotalAmount)
                    </th>
                    <th>
                        @Html.Label("Action")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.VoucherNo)</td>
                        <td>@Html.DisplayFor(modelItem => item.IssueDate)</td>
                        <td>@Html.DisplayFor(modelItem => item.Requester)</td>
                        <td>@Html.DisplayFor(modelItem => item.Causes)</td>
                        @{
                            // to show currency format as -$#,###.00
                            CultureInfo culture = CultureInfo.CreateSpecificCulture("en-US");
                            culture.NumberFormat.CurrencyNegativePattern = 1;
                            var amt = string.Format(culture, "{0:C}", item.VoucherTotalAmount);

                            var textColor = (item.VoucherTotalAmount < 0) ? "text-danger" : "";
                        }
                        <td><span class="@textColor">@amt</span></td>
                        <td>
                            @Html.ActionLink("Approve / Reject", "MakeApproval", "AdjustmentVoucher", new { id = item.VoucherNo }, new { })
                        </td>
                    </tr>
                 }
            </tbody>
        </table>
    }
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.ActionLink("Voucher Number", "Index", new { sortOrder = ViewBag.NumberSortParm, status = ViewBag.Status })
                </th>
                <th>
                    @Html.DisplayNameFor(i => model.IssueDate)
                </th>
                <th>
                    @Html.DisplayNameFor(i => model.Requester)
                </th>
                <th>
                    @Html.DisplayNameFor(i => model.Causes)
                </th>
                <th>
                    @Html.DisplayNameFor(i => model.ApprovalDate)
                </th>
                <th>
                    @Html.DisplayNameFor(i => model.Approver)
                </th>
                <th>
                    @Html.Label("Action")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.VoucherNo)</td>
                    <td>@Html.DisplayFor(modelItem => item.IssueDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.Requester)</td>
                    <td>@Html.DisplayFor(modelItem => item.Causes)</td>
                    <td>@Html.DisplayFor(modelItem => item.ApprovalDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.Approver)</td>
                    <td>
                        @Html.ActionLink("Details", "ShowDetail", "AdjustmentVoucher", new { id = item.VoucherNo }, new { })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    }
}

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, status = ViewBag.Status }))

ADprojrct-System-master/Inventory/Inventory-mvc/Views/AdjustmentVoucher/MakeApproval.cshtml
@model IEnumerable<Inventory_mvc.ViewModel.AdjustmentVoucherViewModel>

@using System.Globalization;

@{
    ViewBag.Title = "MakeApproval";

    var record = Model.First();

    var textColor = "";
    var amt = "";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];

    CultureInfo culture = CultureInfo.CreateSpecificCulture("en-US");
    culture.NumberFormat.CurrencyNegativePattern = 1;
}

<h2>Process Adjustment Voucher</h2>


<br />

@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}


@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}


<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.VoucherNo):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@record.VoucherNo</label>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.IssueDate):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">
            @Html.DisplayFor(model => record.IssueDate)
        </label>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.Requester):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@record.Requester</label>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.Causes):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@record.Causes</label>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.VoucherTotalAmount):</label>
    <div class="col-sm-10">
        @{
            // to show currency format as -$#,###.00
            amt = string.Format(culture, "{0:C}", record.VoucherTotalAmount);
            textColor = (record.VoucherTotalAmount < 0) ? "text-danger" : "";
        }
        <label class="col-sm-2 col-form-label @textColor">
            @amt
        </label>
    </div>
</div>

@using (Html.BeginForm("MakeApproval", "AdjustmentVoucher",new { id = record.VoucherNo }, FormMethod.Post, new { @class = "form", id = "editForm" }))
{
    <textarea name="remarks" class="form-control" rows="4" cols="10" placeholder="Write some message here..."></textarea>
    <br />
    <button type="submit" name="submitButton" value="Approve" class="btn btn-success">Approve</button>
    <button type="submit" name="submitButton" value="Reject" class="btn btn-danger">Reject</button>
}


<br />

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ItemCode)</th>
            <th>@Html.DisplayNameFor(model => model.StationeryDescription)</th>
            <th>@Html.DisplayNameFor(model => model.UOM)</th>
            <th>@Html.DisplayNameFor(model => model.Quantity)</th>
            <th>@Html.Label("Amount Adjusted")</th>
            <th>@Html.DisplayNameFor(model => model.Reason)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.ItemCode)</td>
                <td>@Html.DisplayFor(modelItem => item.StationeryDescription)</td>
                <td>@Html.DisplayFor(modelItem => item.UOM)</td>
                @if (item.Quantity > 0)
                {
                    // to show currency format as -$#,###.00
                    amt = string.Format(culture, "{0:C}", 0);
                    textColor = "";

                    <td><span class="text-success">+@item.Quantity</span></td>
                    <td><span>@amt</span></td>
                }
                else
                {
                    // to show currency format as -$#,###.00
                    amt = string.Format(culture, "{0:C}", item.Quantity * item.Price);
                    textColor = "text-danger";

                    <td><span class="text-danger">@item.Quantity</span></td>
                    <td><span class="@textColor">@amt</span></td>
                }
                <td>@Html.DisplayFor(modelItem => item.Reason)</td>
            </tr>
        }
    </tbody>
</table>





@Html.ActionLink("Back to List", "Index")

ADprojrct-System-master/Inventory/Inventory-mvc/Views/AdjustmentVoucher/NewVoucher.cshtml
<script src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />

@model IEnumerable<Inventory_mvc.ViewModel.AdjustmentVoucherViewModel>

@{
    ViewBag.Title = "NewVoucher";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Adjustment Voucher</h2>

<br />
<button type="button" class="btn btn-success" id="addItemBtn" data-toggle="modal" data-target="#addItemModal">Add New Item</button>
<br />
<br />


@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}

<br />

@if (Model.Count() == 0)
{
    <h4><i>There is not item in adjustment voucher.</i></h4>
}
else
{
    using (Html.BeginForm("SubmitVoucher", "AdjustmentVoucher", FormMethod.Post, new { @class = "form", @id = "voucherForm" }))
    {
        <table class="table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.ItemCode)</th>
                    <th>@Html.DisplayNameFor(model => model.StationeryDescription)</th>
                    <th>@Html.DisplayNameFor(model => model.UOM)</th>
                    <th>@Html.DisplayNameFor(model => model.Quantity)</th>
                    <th>@Html.DisplayNameFor(model => model.Reason)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    var item = Model.ElementAt(i);

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ItemCode)
                            <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode" />
                            <input type="hidden" name="[@i].Price" value="@item.Price" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StationeryDescription)
                            <input type="hidden" name="[@i].StationeryDescription" value="@item.StationeryDescription" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UOM)
                            <input type="hidden" name="[@i].UOM" value="@item.UOM" />
                        </td>
                        <td>
                            <input type="number" name="[@i].Quantity" value="@item.Quantity" class="form-control form-control-sm" />
                        </td>
                        <td>
                            <input type="text" name="[@i].Reason" value="@item.Reason" class="form-control form-control-sm" />
                        </td>
                        <td>
                            <a href="#" data-bind="@item.ItemCode" onclick="RemoveItem('@item.ItemCode')" class="removeBtn">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <br />
        <input type="submit" value="Submit Adjustment Voucher" class="btn btn-success" onclick = "return confirm('Are you sure you want to submit the adjustment voucher?');"/>
        <a href="@Url.Action("ClearAllItemInVoucher", "AdjustmentVoucher" )">
            <input type="button" value="Clear All" class="btn btn-danger" onclick = "return confirm('Are you sure you want to claer all items in the voucher?');"/>
        </a>
        <br />

    }

}


<!-- The below code is for the modal dialog -->
<div class="modal fade" id="addItemModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="addItemModalBodyDiv">
            @using (Html.BeginForm("AddItemIntoVoucher", "AdjustmentVoucher", FormMethod.Post, new { @class = "form", @id = "newVoucher" }))
        {
                <div class="modal-header">
                    <h3 class="modal-title">Add Discrepancy</h3>
                </div>

                <div class="modal-body">

                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.ItemCode)</label>
                        <br />
                        <!-- Combobox -->
                        <select class="js-data-example-ajax js-states form-control" style="width: 100%" name="itemCode" required>
                            <option></option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Quantity)</label>                        
                        <input type="number" class="form-control" placeholder="Quantity" name="quantity" required />
                    </div>

                    <div class="form-group">
                        <label>@Html.DisplayNameFor(model => model.Reason)</label>
                        <input type="text" class="form-control" placeholder="Reason" name="reason" />
                    </div>

                </div>

                <div class="modal-footer">
                    <input type="submit" value="Add" class="btn btn-success" />
                    <input type="button" value="Cancel" class="btn btn-secondary" data-dismiss="modal" />
                </div>
            }
        </div>
    </div>
</div>



<script>

    $(document).ready(function () {
        $('.js-data-example-ajax').select2({

            ajax: {
                url: '@Url.Action("GetStationeryListJSON", "AdjustmentVoucher")',
                delay: 250,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: data
                    };
                },
                // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
            },

            placeholder: "Input item code",
            //minimumInputLength: 1,
            selectOnClose: true,
            allowClear: true,
            dropdownParent: $('#addItemModal'),
        });

        $(".removeBtn").click(function () {
            var itemCode = $(this).data("bind");

            var myformdata = $("#voucherForm").serializeArray(); // convert form to array
            myformdata.push({ name: "itemCode", value: itemCode }); // add extra key-value pair

            $.ajax({
                type: "POST",
                url: '@Url.Action("RemoveVoucherItem", "AdjustmentVoucher")',
                data: $.param(myformdata), // convert to url-encoded form
                success: function() {
                    window.location.href = '@Url.Action("NewVoucher", "AdjustmentVoucher")?type=remove&itemCode=' + itemCode;
                }
                    });
        });

        $("#addItemBtn").click(function () {

            var myformdata = $("#voucherForm").serializeArray(); // convert form to array

            $.ajax({
                type: "POST",
                url: '@Url.Action("SaveTemporaryValue", "AdjustmentVoucher")',
                data: $.param(myformdata), // convert to url-encoded form
            });
        });

    });
</script>