ADprojrct-System-master/Inventory/Inventory-mvc/Controllers/ListRequisitionsController.cs
using Inventory_mvc.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_mvc.Models;
using Inventory_mvc.ViewModel;
using Inventory_mvc.Utilities;
using PagedList;
using Inventory_mvc.Function;


namespace Inventory_mvc.Controllers
{
    public class ListRequisitionsController : Controller
    {
        IStationeryService stationeryService = new StationeryService();
        IRequisitionRecordService requisitionService = new RequisitionRecordService();
        IUserService userService = new UserService();

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult Index(int? page, string sortOrder)
        {
            // Retrieve all requisitions made by current user
            string requesterID = HttpContext.User.Identity.Name;

            if(String.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "date_desc"; // defaut sorting by date desc
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = (sortOrder == "Request Date") ? "date_desc" : "Request Date";
            ViewBag.NumberSortParm = (sortOrder == "Requisition Form Number") ? "number_desc" : "Requisition Form Number";
            ViewBag.StatusSortParm = (sortOrder == "Status") ? "status_desc" : "Status";

            List<Requisition_Record> records = requisitionService.GetSortedRecordsByRequesterID(requesterID, sortOrder);

            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(records.ToPagedList(pageNumber, pageSize));
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult RemoveRecord(int? id)
        {
            int recordNo = (id == null) ? -1 : (int)id;

            if (recordNo == -1)
            {
                return RedirectToAction("Index");
            }

            string requesterID = HttpContext.User.Identity.Name;

            string errorMessage;
            Requisition_Record record = requisitionService.IsUserAuthorizedForRequisition(recordNo, requesterID, out errorMessage);

            if (!String.IsNullOrEmpty(errorMessage))
            {
                TempData["ErrorMessage"] = errorMessage;
                return RedirectToAction("Index");
            }


            if (record.status != RequisitionStatus.PENDING_APPROVAL)
            {
                TempData["ErrorMessage"] = String.Format("Cannot remove requisition no. {0}", record.requisitionNo);
            }
            else
            {
                if (requisitionService.DeleteRequisition(recordNo))
                {
                    TempData["SuccessMessage"] = String.Format("Requisition no. {0} was removed.", record.requisitionNo);
                }
                else
                {
                    TempData["ErrorMessage"] = String.Format("Error Writing to Database");
                }
            }

            return RedirectToAction("Index");
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        [HttpGet]
        public ActionResult EditRecord(int? id)
        {
            int recordNo = (id == null) ? -1 : (int)id;

            if (recordNo == -1)
            {
                return RedirectToAction("Index");
            }

            string requesterID = HttpContext.User.Identity.Name;

            string errorMessage;
            Requisition_Record record = requisitionService.IsUserAuthorizedForRequisition(recordNo, requesterID, out errorMessage);

            if (!String.IsNullOrEmpty(errorMessage))
            {
                TempData["ErrorMessage"] = errorMessage;
                return RedirectToAction("Index");
            }

            if (record.status != RequisitionStatus.PENDING_APPROVAL)
            {
                TempData["ErrorMessage"] = String.Format("Requisition has been approved and cannot be edited.");
                return RedirectToAction("Index");
            }


            List<RequisitionDetailViewModel> vmList = requisitionService.GetViewModelFromRequisitionRecord(record);

            // Set string for display
            string approvalStatus = (record.status == RequisitionStatus.PENDING_APPROVAL) ? RequisitionStatus.PENDING_APPROVAL : "Approved";

            ViewBag.RequisitionFormNo = record.requisitionNo;
            ViewBag.ApprovalStatus = approvalStatus;

            return View(vmList);
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        [HttpPost]
        public ActionResult EditRecord(List<RequisitionDetailViewModel> vmList)
        {
            foreach(var vm in vmList)
            {
                if (vm.RequestQty < 1)
                {
                    TempData["ErrorMessage"] = String.Format("Quantity of {0} must be greater than or equal to 1", vm.Description);
                    return RedirectToAction("EditRecord", vmList);
                }
            }

            string errorMessage;
            
            if (requisitionService.UpdateRequisitionDetails(vmList, out errorMessage))
            {
                TempData["SuccessMessage"] = String.Format("Requisition form no. {0} has been updated.", vmList.First().RequisitionNo);
                return RedirectToAction("ShowDetail", new { id = vmList.First().RequisitionNo });
            }
            else
            {
                TempData["ErrorMessage"] = errorMessage;
                return RedirectToAction("EditRecord", vmList);
            }
        }

        [RoleAuthorize]
        // CK - Employee | User Representative | Store Clerk | Store Supervisor
        public ActionResult ShowDetail(int? id)
        {
            int recordNo = (id == null) ? -1 : (int) id;

            if(recordNo == -1)
            {
                return RedirectToAction("Index");
            }

            string requesterID = HttpContext.User.Identity.Name;

            string errorMessage;
            Requisition_Record record = requisitionService.IsUserAuthorizedForRequisition(recordNo, requesterID, out errorMessage);

            if (!String.IsNullOrEmpty(errorMessage))
            {
                TempData["ErrorMessage"] = errorMessage;
                return RedirectToAction("Index");
            }

            List<RequisitionDetailViewModel> vmList = requisitionService.GetViewModelFromRequisitionRecord(record);

            // set text for display
            string approvalStatus = (record.status == RequisitionStatus.PENDING_APPROVAL) ? RequisitionStatus.PENDING_APPROVAL : "Approved";

            ViewBag.RequisitionFormNo = record.requisitionNo;
            ViewBag.ApprovalStatus = approvalStatus;

            return View(vmList);
        }


        
    }
}

ADprojrct-System-master/Inventory/Inventory-mvc/Views/ListRequisitions/EditRecord.cshtml
@model IEnumerable<Inventory_mvc.ViewModel.RequisitionDetailViewModel>

@{
    ViewBag.Title = "EditRecord";

    var errorMessage = TempData["ErrorMessage"];
}

<h2>Edit Requisition</h2>
<br />


<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.RequisitionNo):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@ViewBag.RequisitionFormNo</label>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">Approval Status:</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@ViewBag.ApprovalStatus</label>
    </div>
</div>

<br />
@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

<br />
@using (Html.BeginForm("EditRecord", "ListRequisitions", null, FormMethod.Post, new { @class = "form", id = "editForm" }))
{

    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>@Html.DisplayNameFor(model => model.UOM)</th>
                <th>@Html.DisplayNameFor(model => model.RequestQty)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @Html.AntiForgeryToken()

            @for (int i = 0; i < Model.Count(); i++)
            {
                var item = Model.ElementAt(i);

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <tr>
                    <td>
                        <input type="hidden" name="[@i].RequisitionNo" value="@item.RequisitionNo" />
                        <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode" />
                        <input type="hidden" name="[@i].Description" value="@item.Description" />
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UOM)
                    </td>
                    <td>
                        <input type="number" min="1" value="@item.RequestQty" name="[@i].RequestQty" class="form-control"/>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <input type="submit" value="Confirm Changes" class="btn btn-success" />
    <input type="button" value="Cancel"  class="btn btn-secondary" onclick="window.location.href='@Url.Action("ShowDetail", new { id = ViewBag.RequisitionFormNo })'" />
        <br />
}


<!-- The below code is for the modal dialog -->
<div class="modal fade" id="editItemModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="editItemModalBodyDiv">
        </div>
    </div>
</div>

ADprojrct-System-master/Inventory/Inventory-mvc/Views/ListRequisitions/Index.cshtml
@model PagedList.IPagedList<Inventory_mvc.Models.Requisition_Record>

@using PagedList.Mvc;
@using Inventory_mvc.Utilities;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Index";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Requisition List</h2>

<br />
@Html.ActionLink("Make New Requisition", "NewRequisition", "RaiseRequisition", null, new { @class = "btn btn-success" })
<br />
<br />


@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}


@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}

@if (Model.Count() == 0)
{
    <h4><i>Your requistion list is empty.</i></h4>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.ActionLink("Requisition Form No.", "Index", new { sortOrder = ViewBag.NumberSortParm })
                </th>
                <th>
                    @Html.ActionLink("Request Date", "Index", new { sortOrder = ViewBag.DateSortParm })
                </th>
                <th>
                    @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.StatusSortParm })
                </th>
                <th>@Html.Label("Action")</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.requisitionNo)</td>
                    <td>@Html.DisplayFor(modelItem => item.requestDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.status)</td>
                    <td>
                        @Html.ActionLink("Details", "ShowDetail", "ListRequisitions", new { id = item.requisitionNo }, new { })
                        @if (item.status == RequisitionStatus.PENDING_APPROVAL)
                    {
                            @:| @Html.ActionLink("Edit", "EditRecord", "ListRequisitions", new { id = item.requisitionNo }, new { })
                            @:| @Html.ActionLink("Remove", "RemoveRecord", "ListRequisitions", new { id = item.requisitionNo }, new { })
                    }
                    </td>
                </tr>
            }
        </tbody>
    </table>


    @:Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort }))


}

ADprojrct-System-master/Inventory/Inventory-mvc/Views/ListRequisitions/ShowDetail.cshtml
@model IEnumerable<Inventory_mvc.ViewModel.RequisitionDetailViewModel>

@using Inventory_mvc.Utilities;

@{
    ViewBag.Title = "ShowDetail";

    var successMessage = TempData["SuccessMessage"];

}

<h2>Requisition Details</h2>
<br />


<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.RequisitionNo):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@ViewBag.RequisitionFormNo</label>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">Approval Status:</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@ViewBag.ApprovalStatus</label>
    </div>
</div>

<br/>
@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}
<br />
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>@Html.DisplayNameFor(model => model.UOM)</th>
            <th>@Html.DisplayNameFor(model => model.RequestQty)</th>
            <th>@Html.DisplayNameFor(model => model.ReceivedQty)</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                <td>@Html.DisplayFor(modelItem => item.UOM)</td>
                <td>@Html.DisplayFor(modelItem => item.RequestQty)</td>
                <td>@Html.DisplayFor(modelItem => item.ReceivedQty)</td>
            </tr>
        }
    </tbody>
</table>

<br />
@if (ViewBag.ApprovalStatus == RequisitionStatus.PENDING_APPROVAL)
{
    @Html.ActionLink("Edit", "EditRecord", "ListRequisitions", new { id = ViewBag.RequisitionFormNo }, new { })
    @:| @Html.ActionLink("Remove", "RemoveRecord", "ListRequisitions", new { id = ViewBag.RequisitionFormNo }, new { }) |
}

@Html.ActionLink("Back to List", "Index")

ADprojrct-System-master/Inventory/Inventory-mvc/Views/ListRequisitions/_EditRecord.cshtml
@model IEnumerable<Inventory_mvc.ViewModel.RequisitionDetailViewModel>

@{
    ViewBag.Title = "EditRecord";


#line default
#line hidden

#line 3 "C:\Users\CK Tan\Source\Repos\ADprojrct-System\Inventory\Inventory-mvc\Views\ListRequisitions\EditRecord.cshtml"

    ViewBag.Title = "EditRecord";

    var editMessage = TempData["EditMessage"];
}

<h2>Requisition Details</h2>
<br />


<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">Requisition Form No.</label>
    <div class="col-sm-10">
        <input type="text" id="formNo" readonly class="form-control-plaintext" value="@ViewBag.RequisitionFormNo">
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">Approval Status</label>
    <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext" value="@ViewBag.ApprovalStatus">
    </div>
</div>

<br />
@if (editMessage != null)
{
    <div class="alert alert-success">
        @editMessage.ToString()
    </div>
}

@if (editMessage != null)
{


#line default
#line hidden

#line 7 "C:\Users\CK Tan\Source\Repos\ADprojrct-System\Inventory\Inventory-mvc\Views\ListRequisitions\EditRecord.cshtml"
    __o = editMessage.ToString();


#line default
#line hidden

#line 8 "C:\Users\CK Tan\Source\Repos\ADprojrct-System\Inventory\Inventory-mvc\Views\ListRequisitions\EditRecord.cshtml"

}

#line default
#line hidden

#line 9 "C:\Users\CK Tan\Source\Repos\ADprojrct-System\Inventory\Inventory-mvc\Views\ListRequisitions\EditRecord.cshtml"
if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

<br />
<table class="table">
    <thead>
        <tr>
            <th>@Html.Label("Description")</th>
            <th>@Html.Label("Request Quantity")</th>
            <th>@Html.Label("UOM")</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            var formID = "form-" + item.ItemCode;

            using (Html.BeginForm("EditRecord", "ListRequisitions", null, FormMethod.Post, new { @class = "form", id = formID }))
            {

                @Html.HiddenFor(modelItem => item.ItemCode, new { htmlAttributes = new { name = "itemCode" } })
                @Html.HiddenFor(modelItem => item.RequisitionNo, new { htmlAttributes = new { name = "id" } })

                <tr>

                    <td>
                        <input type="hidden" name="id" value="@item.RequisitionNo" />
                        <input type="hidden" name="itemCode" value="@item.ItemCode" />
                        <input type="hidden" name="description" value="@item.Description" />
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <span class="" id="displayQty-@item.ItemCode">
                            @Html.DisplayFor(modelItem => item.RequestQty, new { htmlAttributes = new { @class = "" } })
                        </span>
                        <span class="d-none" id="editQty-@item.ItemCode">
                            <input type="number" name="quantity" value="@item.RequestQty" min="1" class="form-control" placeholder="Quantity" />
                        </span>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UOM)
                    </td>
                    <td>
                        <span class="" id="editBtn-@item.ItemCode">
                            <a href="#" onclick="editBtnClick('@item.ItemCode')">Edit</a>
                        </span>
                        <span class="d-none" id="showBtnIfEdit-@item.ItemCode">
                            <a href="#" onclick="submitBtnClick('@item.ItemCode')">Save Change</a> |
                            <a href="#" onclick="cancelBtnClick('@item.ItemCode')">Cancel</a>
                        </span>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<br />
@Html.ActionLink("Back to List", "Index")

<!-- The below code is for the modal dialog -->
<div class="modal fade" id="editItemModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="editItemModalBodyDiv">
        </div>
    </div>
</div>

<script>

    function editBtnClick(itemCode) {

        var d1 = document.getElementById("editBtn-" + itemCode);
        d1.className += " d-none";

        var d2 = document.getElementById("showBtnIfEdit-" + itemCode);
        d2.className -= " d-none";

        var d3 = document.getElementById("displayQty-" + itemCode);
        d3.className += " d-none";

        var d4 = document.getElementById("editQty-" + itemCode);
        d4.className -= " d-none";
    };


    function cancelBtnClick(itemCode) {

        var d1 = document.getElementById("editBtn-" + itemCode);
        d1.className -= " d-none";

        var d2 = document.getElementById("showBtnIfEdit-" + itemCode);
        d2.className += " d-none";

        var d3 = document.getElementById("displayQty-" + itemCode);
        d3.className -= " d-none";

        var d4 = document.getElementById("editQty-" + itemCode);
        d4.className += " d-none";
    };

    function submitBtnClick(itemCode) {
        var form = document.getElementById("form-" + itemCode);
        form.submit();
    };


</script>