ADprojrct-System-master/Inventory/Inventory-mvc/Controllers/InventoryCheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_mvc.Service;
using Inventory_mvc.Models;
using Inventory_mvc.ViewModel;
using PagedList;
using System.Transactions;
using Rotativa.MVC;
using Inventory_mvc.Function;

namespace Inventory_mvc.Controllers
{
    public class InventoryCheckController : Controller
    {
        IStationeryService stationeryService = new StationeryService();
        IAdjustmentVoucherService adjustmentVoucherService = new AdjustmentVoucherService();
        IInventoryStatusRecordService invetoryCheckService = new InventoryStatusRecordService();

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        public ActionResult Index()
        {
            List<DateTime> dates = invetoryCheckService.ListAllStockCheckDate();
            ViewBag.Dates = dates;

            return View();
        }

        [RoleAuthorize]
        // CK - Store Clerk | Store Supervisor | Store Manager
        public ActionResult ShowDetails(DateTime? date = null)
        {
            if (date == null)
            {
                return RedirectToAction("Index");
            }

            List<InventoryCheckViewModel> vmList = invetoryCheckService.FindInventoryStatusRecordsByDate((DateTime) date);

            if(vmList.Count == 0)
            {
                TempData["ErrorMessage"] = "Non-existing inventory check record.";
            }

            return View(vmList);
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpGet]
        public ActionResult GenerateInventoryChecklist()
        {
            if (HttpContext.Application["InventoryChecklist"] != null)
            {
                // must complete current stock check first before generate new one
                TempData["ErrorMessage"] = String.Format("Please complete or cancel current stock check before generate another checklist.");
                return RedirectToAction("ProcessInventoryCheck");
            }

            ViewBag.CategoryList = stationeryService.GetAllCategory();

            List<Category> categories = stationeryService.GetAllCategory();
            List<SelectListItem> selectList = new List<SelectListItem>();
            foreach(Category c in categories)
            {
                SelectListItem item = new SelectListItem()
                {
                    Text = c.categoryName,
                    Value = c.categoryID.ToString()
                };

                selectList.Add(item);
            }

            ViewBag.SelectList = selectList;


            return View();
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpPost]
        public ActionResult GenerateInventoryChecklist(int[] categorylistbox = null)
        {

            string errorMessage = null;
            List<string> checkedCategories;

            if(categorylistbox == null)
            {
                errorMessage = "Please select at least one category.";
            }
            else if(adjustmentVoucherService.GetPendingVoucherCount() != 0)
            {
                // check whether has pending adjustment voucher
                errorMessage = String.Format("There are {0} pending adjustment voucher(s). Please process all vouchers first before generate the list.", adjustmentVoucherService.GetPendingVoucherCount());
            }
            else if(invetoryCheckService.IsStockCheckConductedForCategoriesOnDate(DateTime.Today, categorylistbox, out checkedCategories))
            {
                errorMessage = String.Format("Stock check results for categories: {0} has been submitted today.", String.Join(", ", checkedCategories));
            }

            if (!String.IsNullOrEmpty(errorMessage))
            {
                TempData["ErrorMessage"] = errorMessage;
                return RedirectToAction("GenerateInventoryChecklist");
            }

            List<InventoryCheckViewModel> vmList = invetoryCheckService.GetInventoryChecklistBasedOnCategory(categorylistbox);

            if(vmList.Count == 0)
            {
                TempData["ErrorMessage"] = "There is no stationery for selected categories.";
                return RedirectToAction("GenerateInventoryChecklist");
            }

            HttpContext.Application.Lock();
            HttpContext.Application["InventoryChecklist"] = vmList;
            HttpContext.Application.UnLock();

            return RedirectToAction("ProcessInventoryCheck", vmList);
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpGet]
        public ActionResult ProcessInventoryCheck(int? page)
        {
            HttpContext.Application.Lock();
            List<InventoryCheckViewModel> stockchecklist = HttpContext.Application["InventoryChecklist"] as List<InventoryCheckViewModel>;
            HttpContext.Application.UnLock();

            if (stockchecklist == null) // not yet generate any list
            {
                return RedirectToAction("GenerateInventoryChecklist");
            }

            ViewBag.Page = page;

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(stockchecklist.ToPagedList(pageNumber, pageSize));
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpGet]
        public ActionResult GenerateStockCheckList()
        {
            HttpContext.Application.Lock();
            List<InventoryCheckViewModel> stockchecklist = HttpContext.Application["InventoryChecklist"] as List<InventoryCheckViewModel>;
            HttpContext.Application.UnLock();

            if (stockchecklist == null) // not yet generate any list
            {
                return RedirectToAction("GenerateInventoryChecklist");
            }

            string fileName = String.Format("Inventory_Stock_Checklist_on_{0}.pdf", stockchecklist.First().StockCheckDate.ToLongDateString());
            return new ViewAsPdf("_StockCheckListPDF", stockchecklist) { FileName = fileName };
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpPost]
        public void SaveTemporaryValue(List<InventoryCheckViewModel> checklist)
        {
            if(checklist != null || checklist.Count != 0)
            {
                HttpContext.Application.Lock();
                List<InventoryCheckViewModel> stockchecklist = HttpContext.Application["InventoryChecklist"] as List<InventoryCheckViewModel>;
                HttpContext.Application.UnLock();

                foreach(InventoryCheckViewModel item in checklist)
                {
                    InventoryCheckViewModel vm = stockchecklist.Find(x => x.ItemCode == item.ItemCode);
                    vm.ActualQuantity = item.ActualQuantity;
                }

                HttpContext.Application.Lock();
                HttpContext.Application["InventoryChecklist"] = stockchecklist;
                HttpContext.Application.UnLock();
            }

        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpGet]
        public ActionResult CancelCurrentStockCheck()
        {
            HttpContext.Application.Lock();
            HttpContext.Application["InventoryChecklist"] = null;
            HttpContext.Application.UnLock();

            TempData["SuccessMessage"] = "Stock check has been cancelled.";
            return RedirectToAction("GenerateInventoryChecklist");
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpPost]
        public ActionResult SubmitInventoryCheckResult()
        {
            HttpContext.Application.Lock();
            List<InventoryCheckViewModel> stockchecklist = HttpContext.Application["InventoryChecklist"] as List<InventoryCheckViewModel>;
            HttpContext.Application.UnLock();

            // find discrepancy
            List<InventoryCheckViewModel> discrepancylist = invetoryCheckService.ConvertStockChecklistToDiscrepancyList(stockchecklist);

            if(discrepancylist.Count() == 0) // if not disprecancy then save into database directly
            {
                try
                {
                    invetoryCheckService.SaveInventoryCheckResult(stockchecklist);

                    // clear list
                    HttpContext.Application.Lock();
                    HttpContext.Application["InventoryChecklist"] = null;
                    HttpContext.Application.UnLock();

                    TempData["SuccessMessage"] = "Stock check result has been submitted.";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["ErrorMessage"] = e.Message;
                    return RedirectToAction("ProcessInventoryCheck");
                }
            }
            else
            {
                // show discrepany report
                return View(discrepancylist);
            }
        }

        [RoleAuthorize]
        // CK - Store Clerk
        [HttpPost]
        public ActionResult ConfirmInventoryCheckResult(List<InventoryCheckViewModel> discrepancylist)
        {
            HttpContext.Application.Lock();
            List<InventoryCheckViewModel> stockchecklist = HttpContext.Application["InventoryChecklist"] as List<InventoryCheckViewModel>;
            HttpContext.Application.UnLock();

            foreach(var item in discrepancylist)
            {
                InventoryCheckViewModel vm = stockchecklist.Find(x => x.ItemCode == item.ItemCode);
                vm.Remarks = item.Remarks;
            }

            HttpContext.Application.Lock();
            HttpContext.Application["InventoryChecklist"] = stockchecklist;
            HttpContext.Application.UnLock();

            string requesterID = HttpContext.User.Identity.Name;

            using (TransactionScope ts = new TransactionScope())
            {
                try
                {
                    try

ADprojrct-System-master/Inventory/Inventory-mvc/Views/InventoryCheck/GenerateInventoryCheckList.cshtml
<style>
    #ListBox
    {
          height: 340px;
    }
</style>

@{
    ViewBag.Title = "GenerateInventoryCheckList";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Generate Inventory Checklist</h2>

<br />


@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}

<h4>Select categories to generate checklist:</h4>

    @using (Html.BeginForm("GenerateInventoryChecklist", "InventoryCheck", FormMethod.Post, new { @class = "form" }))
    {
        <div class="row">
            <div class="form-group col-xs-3">
                @Html.ListBox("categorylistbox", ViewBag.SelectList as IEnumerable<SelectListItem>, new { @class = "form-control", @id="ListBox"})
            </div>
        </div>
        <input type="submit" value="Generate List" class="btn btn-primary" />
    }

ADprojrct-System-master/Inventory/Inventory-mvc/Views/InventoryCheck/Index.cshtml
@{
    ViewBag.Title = "Index";

    List<DateTime> dates = ViewBag.Dates;

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Inventory Check Records</h2>

<br />


@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}

<table class="table" style="width=50%">
    <thead>
        <tr>
            <th>Stock Check Dates</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var date in dates)
        {
            <tr>
                <td>@String.Format("{0:dd/MM/yyyy}", date)</td>
                <td>
                    @Html.ActionLink("Details", "ShowDetails", new { date = date })
                </td>
            </tr>
        }
    </tbody>
</table>

ADprojrct-System-master/Inventory/Inventory-mvc/Views/InventoryCheck/ProcessInventoryCheck.cshtml
@model PagedList.IPagedList<Inventory_mvc.ViewModel.InventoryCheckViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "ProcessInventoryCheck";

    var model = Model.First();

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Record Inventory Check Result</h2>

<br />
@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}

@Html.ActionLink("Download Checklist as PDF", "GenerateStockCheckList")
<br />
<br />

@using (Html.BeginForm("SubmitInventoryCheckResult", "InventoryCheck", new {  }, FormMethod.Post, new { @class = "form", @id="checkForm" }))
{
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(i => model.CategoryName)</th>
                <th>@Html.DisplayNameFor(i => model.ItemCode )</th>
                <th>@Html.DisplayNameFor(i => model.StationeryDescription)</th>
                <th>@Html.DisplayNameFor(i => model.UOM)</th>
                <th>@Html.DisplayNameFor(i => model.Location)</th>
                <th>@Html.DisplayNameFor(i => model.StockQuantity)</th>
                <th>@Html.DisplayNameFor(i => model.ActualQuantity)</th>
            </tr>
        </thead>
        <tbody>
            @for(int i = 0; i < Model.Count(); i++)
            {
                var item = Model.ElementAt(i);
                <tr>
                    <td>
                        @Html.DisplayFor(p => item.CategoryName)
                        <input type="hidden" name="[@i].CategoryName" value="@item.CategoryName" />
                        <input type="hidden" name="[@i].CategoryID" value="@item.CategoryID" />
                    </td>
                    <td>
                        @Html.DisplayFor(p => item.ItemCode)
                        <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode"/>
                    </td>
                    <td>
                        @Html.DisplayFor(p => item.StationeryDescription)
                        <input type="hidden" name="[@i].StationeryDescription" value="@item.StationeryDescription" />
                    </td>
                    <td>
                        @Html.DisplayFor(p => item.UOM)
                        <input type="hidden" name="[@i].UOM" value="@item.UOM" />
                    </td>
                    <td>
                        @Html.DisplayFor(p => item.Location)
                        <input type="hidden" name="[@i].Location" value="@item.Location" />
                    </td>
                    <td>
                        @Html.DisplayFor(p => item.StockQuantity)
                        <input type="hidden" name="[@i].StockQuantity" value="@item.StockQuantity" />
                    </td>
                    <td>
                        <input type="number" name="[@i].ActualQuantity"  value="@item.ActualQuantity" class="form-control" min="0" onchange="SaveData()"  required />
                    </td>
                </tr>
            }
        </tbody>
    </table>

    

    @:Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("ProcessInventoryCheck", new { page }))


    <input type="submit" value="Submit Stock Check Result" class="btn btn-success" />
    <input type="button" value="Cancel Stock Check" onclick="CancelStockCheck()" class="btn btn-danger" />
}

                     
<script>
    function SaveData()
    {
        var myformdata = $("#checkForm").serializeArray(); // convert form to array

        $.ajax({
            type: "POST",
            url: '@Url.Action("SaveTemporaryValue", "InventoryCheck")',
            data: $.param(myformdata), // convert to url-encoded form
        });
    }


    function CancelStockCheck()
    {
        window.location.href = '@Url.Action("CancelCurrentStockCheck", "InventoryCheck")';
    }
</script>

ADprojrct-System-master/Inventory/Inventory-mvc/Views/InventoryCheck/ShowDetails.cshtml
@model IEnumerable<Inventory_mvc.ViewModel.InventoryCheckViewModel>


@{
    ViewBag.Title = "ShowDetails";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Inventory Check Details</h2>

<br />


@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}

<div class="form-group row">
    <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.StockCheckDate):</label>
    <div class="col-sm-10">
        <label class="col-sm-2 col-form-label">@Html.DisplayFor(model => model.First().StockCheckDate)</label>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ItemCode)</th>
            <th>@Html.DisplayNameFor(model => model.StationeryDescription)</th>
            <th>@Html.DisplayNameFor(model => model.UOM)</th>
            <th>@Html.DisplayNameFor(model => model.StockQuantity)</th>
            <th>@Html.DisplayNameFor(model => model.ActualQuantity)</th>
            <th>@Html.DisplayNameFor(model => model.Discrepancy)</th>
            <th>@Html.DisplayNameFor(model => model.Remarks)</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count(); i++)
        {
            var item = Model.ElementAt(i);

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCode)
                    <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StationeryDescription)
                    <input type="hidden" name="[@i].StationeryDescription" value="@item.StationeryDescription" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UOM)
                    <input type="hidden" name="[@i].UOM" value="@item.UOM" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StockQuantity)
                    <input type="hidden" name="[@i].StockQuantity" value="@item.StockQuantity" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActualQuantity)
                    <input type="hidden" name="[@i].ActualQuantity" value="@item.ActualQuantity" />
                </td>
                @if (item.Discrepancy >= 0)
                {
                    <td>
                        <span class="text-success">+@item.Discrepancy</span>
                    </td>
                }
                else
                {
                    <td>
                        <span class="text-danger">@item.Discrepancy</span>
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Remarks)
                </td>
            </tr>
        }
    </tbody>
</table>



@Html.ActionLink("Back to Inventory Check List", "Index")

ADprojrct-System-master/Inventory/Inventory-mvc/Views/InventoryCheck/SubmitInventoryCheckResult.cshtml
@model IEnumerable<Inventory_mvc.ViewModel.InventoryCheckViewModel>

@{
    ViewBag.Title = "SubmitInventoryCheckResult";

    var successMessage = TempData["SuccessMessage"];
    var errorMessage = TempData["ErrorMessage"];
    var warningMessage = TempData["WarningMessage"];
}

<h2>Inventory Check Discrepancy Report</h2>

<br />
@if (successMessage != null)
{
    <div class="alert alert-success">
        @successMessage.ToString()
    </div>
}

@if (errorMessage != null)
{
    <div class="alert alert-danger">
        @errorMessage.ToString()
    </div>
}

@if (warningMessage != null)
{
    <div class="alert alert-warning">
        @warningMessage.ToString()
    </div>
}


@using (Html.BeginForm("ConfirmInventoryCheckResult", "InventoryCheck", new { }, FormMethod.Post, new { @class = "form", @id = "checkForm" }))
{
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.ItemCode)</th>
                <th>@Html.DisplayNameFor(model => model.StationeryDescription)</th>
                <th>@Html.DisplayNameFor(model => model.UOM)</th>
                <th>@Html.DisplayNameFor(model => model.StockQuantity)</th>
                <th>@Html.DisplayNameFor(model => model.ActualQuantity)</th>
                <th>@Html.DisplayNameFor(model => model.Discrepancy)</th>
                <th>@Html.DisplayNameFor(model => model.Remarks)</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count(); i++)
                {
                    var item = Model.ElementAt(i);

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemCode)
                        <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StationeryDescription)
                        <input type="hidden" name="[@i].StationeryDescription" value="@item.StationeryDescription" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UOM)
                        <input type="hidden" name="[@i].UOM" value="@item.UOM" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StockQuantity)
                        <input type="hidden" name="[@i].StockQuantity" value="@item.StockQuantity" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActualQuantity)
                        <input type="hidden" name="[@i].ActualQuantity" value="@item.ActualQuantity" />
                    </td>
                    @if (item.Discrepancy > 0)
                    {
                        <td>
                            <span class="text-success">+@item.Discrepancy</span>
                        </td>
                    }
                    else
                    {
                        <td>
                            <span class="text-danger">@item.Discrepancy</span>
                        </td>
                    }
                    <td>
                        <input type="text" name="[@i].Remarks" placeholder="Input remarks here" class="form-control"/>
                    </td>
                </tr>
            }
        </tbody>
    </table>

        <br />
        <input type="submit" value="Confirm and Submit Discrepancy Report" class="btn btn-success" />
        <input type="button" value="Back To Inventory Checklist" class="btn btn-secondary" onclick="window.location.href='@Url.Action("ProcessInventoryCheck", "InventoryCheck")'" />
        <br />
}

ADprojrct-System-master/Inventory/Inventory-mvc/Views/InventoryCheck/_StockCheckListPDF.cshtml
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@model IEnumerable<Inventory_mvc.ViewModel.InventoryCheckViewModel>

@{
    Layout = null;
    Inventory_mvc.ViewModel.InventoryCheckViewModel first = Model.First();
    string stockCheckDate = Model.First().StockCheckDate.ToLongDateString();
}

<h2 style="text-align: center">Logic University</h2>
<h3 style="text-align: center">Stationery Inventory Checklist</h3>
<h3 style="text-align: center">on @stockCheckDate</h3>
<hr />

<br />
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.CategoryName)</th>
            <th>@Html.DisplayNameFor(model => model.ItemCode)</th>
            <th>@Html.DisplayNameFor(model => model.StationeryDescription)</th>
            <th>@Html.DisplayNameFor(model => model.UOM)</th>
            <th>@Html.DisplayNameFor(model => model.Location)</th>
            <th>@Html.DisplayNameFor(model => model.StockQuantity)</th>
            <th>@Html.DisplayNameFor(model => model.ActualQuantity)</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count(); i++)
        {
            var item = Model.ElementAt(i);
            <tr>
                <td>
                    @Html.DisplayFor(p => item.CategoryName)
                    <input type="hidden" name="[@i].CategoryName" value="@item.CategoryName" />
                    <input type="hidden" name="[@i].CategoryID" value="@item.CategoryID" />
                </td>
                <td>
                    @Html.DisplayFor(p => item.ItemCode)
                    <input type="hidden" name="[@i].ItemCode" value="@item.ItemCode" />
                </td>
                <td>
                    @Html.DisplayFor(p => item.StationeryDescription)
                    <input type="hidden" name="[@i].StationeryDescription" value="@item.StationeryDescription" />
                </td>
                <td>
                    @Html.DisplayFor(p => item.UOM)
                    <input type="hidden" name="[@i].UOM" value="@item.UOM" />
                </td>
                <td>
                    @Html.DisplayFor(p => item.Location)
                    <input type="hidden" name="[@i].Location" value="@item.Location" />
                </td>
                <td>
                    @Html.DisplayFor(p => item.StockQuantity)
                    <input type="hidden" name="[@i].StockQuantity" value="@item.StockQuantity" />
                </td>
                <td>
                    <input type="text" value="" class="form-control"/>
                </td>
            </tr>
        }
    </tbody>
</table>